name: Test Compression
on:
  push:
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        working-directory: ""
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: |
            /test/.m2/repository
          key: test

      - name: Run liquibase update
        run: |
          mkdir -pv test/.m2/repository/
          echo "hello" > test/.m2/repository/hello.txt