name: Test Compression
on:
  push:
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-alpine
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v5
      with:
        script: |
          console.log("process.env['RUNNER_TEMP']="+process.env['RUNNER_TEMP']);
          console.log("process.cwd()="+process.cwd());
          console.log("Home directory = "+require('os').homedir());
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ github.workspace }}/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}