name: Test Compression
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/
        key: cache_0601_03