name: Test Compression
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/
        key: cache_0601_02
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        rm -rf ~/datacache
        mkdir -p ~/datacache
        for y in {0..1};do openssl rand -out ~/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
        du -sh ~/datacache